"""empty message

Revision ID: 0c8356db26a0
Revises: cb3448b387aa
Create Date: 2019-03-29 17:33:05.719318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c8356db26a0'
down_revision = 'cb3448b387aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_phone'), 'bookings', ['phone'], unique=False)
    op.create_index(op.f('ix_bookings_token'), 'bookings', ['token'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_bookings_token'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_phone'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
