"""empty message

Revision ID: 442e9e9b4c16
Revises: 461a84a14783
Create Date: 2019-03-29 22:27:54.333966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442e9e9b4c16'
down_revision = '461a84a14783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_doctors',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_doctors')
    # ### end Alembic commands ###
